/**
 * @typedef {Object} PointFeature - A feature known by its centre (and size, if any)
 * @property {string} id - Stable across builds, so re-importing updates the shapes made before
 * @property {string} name
 * @property {string} type - e.g. 'Crater', 'Mons', 'Lander'; also a tag
 * @property {number} diameterKm - 0 when the source gives none (e.g. landing sites)
 * @property {number} latitude - Degrees, planetocentric
 * @property {number} longitude - Degrees east
 * @property {string} [description] - Becomes the shape's description
 * @property {Record<string, string | number>} [attributes] - Extra properties for the shapes
 */

/**
 * @typedef {Object} PointDataset - A bundled point dataset, generated by `npm run build:shapes`
 * @property {string} id
 * @property {string} name
 * @property {string} source - Where it was downloaded from
 * @property {string} citation
 * @property {string} generatedAt - ISO date
 * @property {PointFeature[]} features
 */

/**
 * @typedef {Object} GdalFeature - A feature of `ogr2ogr -f GeoJSON` output
 * @property {Record<string, string | number | null>} properties
 * @property {{ type: string, coordinates: any } | null} [geometry]
 */

export const IAU_NOMENCLATURE_URL =
  'https://asc-planetarynames-data.s3.us-west-2.amazonaws.com/MOON_nomenclature_center_pts.zip'
export const IAU_NOMENCLATURE_LAYER = 'MOON_nomenclature_center_pts'
// Only the fields the guide uses, to keep the bundled file small
export const IAU_NOMENCLATURE_FIELDS = ['clean_name', 'type', 'diameter', 'center_lat', 'center_lon', 'origin']

/**
 * Builds the bundled named-features dataset from the IAU Gazetteer of Planetary Nomenclature points,
 * as read by GDAL.
 * @param {GdalFeature[]} gdalFeatures
 * @param {Date} [now]
 * @returns {PointDataset}
 */
export function buildNamedFeatures(gdalFeatures, now = new Date()) {
  const features = gdalFeatures.map(({ properties }) => ({
    id: `iau:${properties.clean_name}`,
    name: String(properties.clean_name),
    type: featureType(String(properties.type)),
    diameterKm: Math.round((Number(properties.diameter) || 0) * 1000) / 1000,
    latitude: roundCoordinate(Number(properties.center_lat)),
    longitude: roundCoordinate(Number(properties.center_lon)),
    // What or whom the feature is named after, e.g. 'Italian explorer (1254-1324).'
    ...(properties.origin ? { description: String(properties.origin) } : {}),
  }))
  features.sort((a, b) => a.name.localeCompare(b.name))
  return {
    id: 'iau-named-features',
    name: 'IAU named features',
    source: IAU_NOMENCLATURE_URL,
    citation: 'Gazetteer of Planetary Nomenclature, International Astronomical Union (IAU) Working Group for Planetary System Nomenclature, USGS Astrogeology Science Center',
    generatedAt: now.toISOString(),
    features,
  }
}

/**
 * The IAU types come as 'Crater, craters' (singular, plural): the singular reads better as a tag.
 * @param {string} type
 * @returns {string}
 */
function featureType(type) {
  return type.split(',')[0].trim()
}

/**
 * Five decimals is about 0.3 m on the Moon, well below the positions' own accuracy.
 * @param {number} degrees
 * @returns {number}
 */
export function roundCoordinate(degrees) {
  return Math.round(degrees * 1e5) / 1e5
}
