/**
 * @typedef {import('./iauNomenclature.js').GdalFeature} GdalFeature
 */

/**
 * @typedef {Object} GeologicUnit - One polygon of a geologic unit
 * @property {string} id - Stable across builds, so re-importing updates the shapes made before. Made of the
 *   map's feature number and the part rank in that feature.
 * @property {string} unit - Unit code, e.g. 'Nc'
 * @property {number[][][]} rings - Outer ring then holes, as [longitude, latitude] in degrees
 */

/**
 * @typedef {Object} UnitLegend
 * @property {string} name - e.g. 'Nectarian Crater'
 * @property {string} period - e.g. 'Nectarian'
 * @property {string} color - The map's colour, e.g. '#A68CBE'
 * @property {string} description - The map's description of the unit, and its interpretation when it has one
 */

/**
 * @typedef {Object} GeologyCap - The map's units poleward of a latitude
 * @property {number} latitudeLimit - e.g. -75 for the south cap
 * @property {GeologicUnit[]} units
 */

/**
 * @typedef {Object} GeologyDataset - Generated by `npm run build:shapes`
 * @property {string} id
 * @property {string} name
 * @property {string} source
 * @property {string} citation
 * @property {string} generatedAt - ISO date
 * @property {Record<string, UnitLegend>} legend - By unit code
 * @property {{ south: GeologyCap, north: GeologyCap }} caps
 */

export const UNIFIED_GEOLOGY_URL =
  'https://asc-astropedia.s3.us-west-2.amazonaws.com/Moon/Geology/Unified_Geologic_Map_of_the_Moon_GIS_v2.zip'
const GIS_FOLDER = 'Unified_Geologic_Map_of_the_Moon_GIS/Lunar_GIS/'
export const UNIFIED_GEOLOGY_UNITS = `${GIS_FOLDER}Shapefiles/GeoUnits.shp`
export const UNIFIED_GEOLOGY_DESCRIPTIONS = `${GIS_FOLDER}Symbol_LayerDefinitions/Unified_Geologic_Map_of_the_Moon_DOMU_descriptions.csv`
export const UNIFIED_GEOLOGY_COLORS = `${GIS_FOLDER}Symbol_LayerDefinitions/GeologyUnit_colors.csv`
// Property carrying the map's feature number (shapefile FID) through clipping and exploding, for stable ids
export const UNIFIED_GEOLOGY_FID = 'source_fid'
// Latitude poleward of which units are bundled: the whole map is ~8 million vertices, too much to bundle
export const CAP_LATITUDE = 75
// The map data calls the Orientale Hevelius Formation's secondary crater facies 'Iohs', its description table 'Ios'
const DESCRIPTION_CODES = { Iohs: 'Ios' }

/**
 * Builds the bundled geologic map from the unit polygons of both polar caps (clipped, exploded to single
 * polygons and reprojected to Moon 2000 degrees by GDAL) and the map's description and colour tables.
 * @param {{ south: GdalFeature[], north: GdalFeature[] }} capFeatures - With source_fid, FIRST_Unit and FIRST_Un_1
 *   properties
 * @param {GdalFeature[]} descriptions - Rows of the description table (Unit, Name, Description, Interpretation)
 * @param {GdalFeature[]} colors - Rows of the colour table (unit, color_hex)
 * @param {Date} [now]
 * @returns {GeologyDataset}
 */
export function buildGeologicMap(capFeatures, descriptions, colors, now = new Date()) {
  const descriptionRows = new Map(descriptions.map(({ properties }) => [String(properties.Unit), properties]))
  const colorByUnit = new Map(colors.map(({ properties }) => [String(properties.unit), String(properties.color_hex)]))
  /** @type {Record<string, UnitLegend>} */
  const legend = {}

  /**
   * @param {'south' | 'north'} pole
   * @returns {GeologyCap}
   */
  const toCap = (pole) => {
    const units = []
    // Parts seen so far per map feature: clipping and exploding cut one feature into several polygons
    const partsByFeature = new Map()
    for (const { properties, geometry } of capFeatures[pole]) {
      if (geometry?.type !== 'Polygon') {
        continue
      }
      const feature = properties[UNIFIED_GEOLOGY_FID]
      if (typeof feature !== 'number') {
        throw new Error(`Geologic unit polygon without a ${UNIFIED_GEOLOGY_FID} property in the ${pole} cap`)
      }
      const part = partsByFeature.get(feature) ?? 0
      partsByFeature.set(feature, part + 1)
      const unit = String(properties.FIRST_Unit)
      const row = descriptionRows.get(DESCRIPTION_CODES[unit] || unit)
      legend[unit] ??= {
        name: row ? String(row.Name) : unit,
        period: String(properties.FIRST_Un_1 || ''),
        color: colorByUnit.get(unit) || '',
        description: row ? describeUnit(row) : '',
      }
      units.push({ id: `ugm:${pole}:${feature}:${part}`, unit, rings: geometry.coordinates })
    }
    return { latitudeLimit: pole === 'south' ? -CAP_LATITUDE : CAP_LATITUDE, units }
  }

  return {
    id: 'unified-geologic-map',
    name: 'Geologic units',
    source: UNIFIED_GEOLOGY_URL,
    citation: 'Fortezzo, C.M., Spudis, P.D. and Harrel, S.L. (2020), Release of the Digital Unified Global Geologic Map of the Moon at 1:5,000,000-Scale, LPSC 51, abstract 2760; USGS Astrogeology (CC0)',
    generatedAt: now.toISOString(),
    legend,
    caps: { south: toCap('south'), north: toCap('north') },
  }
}

/**
 * @param {Record<string, string | number | null>} row - A row of the map's description table
 * @returns {string} e.g. 'Rim, wall and floor deposits of craters ... Interpretation: impact crater forms ...'
 */
function describeUnit(row) {
  const interpretation = String(row.Interpretation || '').trim()
  const hasInterpretation = interpretation !== '' && interpretation.toLowerCase() !== 'n/a'
  return hasInterpretation ? `${row.Description} Interpretation: ${interpretation}` : String(row.Description)
}
